### ISSUE TITLE
Accents (é, á, etc.) are not supported

### ISSUE THREAD

**Issue by keanulee** [keanulee/workmate#16]
Seems to be a problem with pebblejs. Ref pebble/pebblejs#11.

**Comment by bhamodi** [comment]
@keanulee - seems to have been addressed recently at: https://github.com/pebble/pebblejs/commit/7d5d6f1363335f042027d380938912d20559d378

**Comment by keanulee** [comment]
Recompiled on Cloudpebble (which presumably has a newer version of pebblejs) and seems to work now.
