### ISSUE TITLE
Sign in is confusing

### ISSUE THREAD

**Issue by benjamin-antupit** [keanulee/workmate#20]
Hello!
First of all, thanks for making this sweet pebble app! I noticed that when I press "Sign in with Google" and then the long URL, I get a Google page with an error. The screenshot is below. I also pasted the URL into Safari on my iPhone and it worked fine. I just found the UI/UX confusing.
![img_b1c1f680404a-1](https://user-images.githubusercontent.com/15172054/44303922-0f7e5600-a302-11e8-878b-fe3ab183b00d.jpeg)

**Comment by ghostwheel** [comment]
I also can not sign in. When I click on the sign in from the app, I get the above screen. When I manually type the URL to a browser (chrome), I see a creen saying "Sign in with Gooogle temporarily disabled for the app. This app has not been verified yet".

**Comment by keanulee** [comment]
Sorry, I don't maintain workmate anymore, and I don't have the time to go through the app verification process.
